//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAdminTemplate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public Element()
        {
            this.Attributes = new HashSet<Attribute>();
            this.ElementVariables = new HashSet<ElementVariable>();
        }
    
        public int Code { get; set; }
        public int OrgID { get; set; }
        public string Name { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<Attribute> Attributes { get; set; }
        public virtual ICollection<ElementVariable> ElementVariables { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
