//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAdminTemplate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hresonanceEntities : DbContext
    {
        public hresonanceEntities()
            : base("name=hresonanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Attribute> Attributes { get; set; }
        public DbSet<AttributeVariable> AttributeVariables { get; set; }
        public DbSet<Element> Elements { get; set; }
        public DbSet<ElementVariable> ElementVariables { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
    }
}
