//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAdminTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public Attribute()
        {
            this.AttributeVariables = new HashSet<AttributeVariable>();
        }
    
        public int Code { get; set; }
        public int ECode { get; set; }
        public string Name { get; set; }
        public string Field { get; set; }
        public string Format { get; set; }
        public string Flag { get; set; }
        public string Input { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<AttributeVariable> AttributeVariables { get; set; }
        public virtual Element Element { get; set; }

        public static List<Attribute> AttributesList = new List<Models.Attribute>();
    }
}
