//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAdminTemplate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModelEntities : DbContext
    {
        public DBModelEntities()
            : base("name=DBModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<AttributeVariable> AttributeVariables { get; set; }
        public virtual DbSet<Element> Elements { get; set; }
        public virtual DbSet<ElementVariable> ElementVariables { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
