//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAdminTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementVariable
    {
        public int Code { get; set; }
        public int ECode { get; set; }
        public string Name { get; set; }
        public decimal CID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Element Element { get; set; }
        //public static List<ElementVariable> ElementsVarList = new List<Models.ElementVariable>();

    }
}
